### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by nth10sd** [asottile/yesqa#140]
```
$ rg -t py --files | xargs python -u -m yesqa
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 184, in <module>
    raise SystemExit(main())
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 179, in main
    retv |= fix_file(filename)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 142, in fix_file
    flake8_results = _run_flake8(path)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 36, in _run_flake8
    lineno, code = line.split('\t')
ValueError: not enough values to unpack (expected 2, got 1)
```

This was probably caused by rev b1b9dc6800fbd0a080431246c65aefab13f987f7. ~~Strangely, I only hit this on GitHub Actions CI but not locally.~~ Edit: It reproduces for me locally.

Versions: yesqa-1.4.0 and flake8-4.0.1 and flake8-print 4.0.1 (using T001 ignores as per stack in next comment) and 5.0.0 (using T201 ignores)

**Comment by nth10sd** [comment]
```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
215	T001
435	T001
442	T001
444	T001
445	T001
449	T001
6     T001 print found.
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 185, in <module>
    raise SystemExit(main())
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 180, in main
    retv |= fix_file(filename)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 143, in fix_file
    flake8_results = _run_flake8(path)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/yesqa.py", line 37, in _run_flake8
    lineno, code = line.split('\t')
ValueError: not enough values to unpack (expected 2, got 1)
```

I stuck in a `print(line)` just above the `lineno, code = line.split('\t')` and that is what I got. My guess is there is a tab in the lines `449	T001` but there is no tab in the line `6     T001 print found.`

**Comment by nth10sd** [comment]
Changing:

```
    for line in out.decode().splitlines():
        lineno, code = line.split("\t")
        ret[int(lineno)].add(code)
```

to:

```
    for line in out.decode().splitlines():
        if "\t" in line:
            lineno, code = line.split("\t")
            ret[int(lineno)].add(code)
```

seems to fix the issue, but I'm not sure if it's the right one.

**Comment by asottile** [comment]
oh, you're using the (useless) `--count` option -- remove that

**Comment by nth10sd** [comment]
> oh, you're using the (useless) `--count` option -- remove that

@asottile So `yesqa` will never work with `statistics = True` in `flake8`? Or is the latter option no longer supported?

**Comment by asottile** [comment]
yeah it never did, and honestly I'm probably going to remove `--count` and `--statistics` from flake8 too, I really don't think they're that useful and one can derive them from the output if they need to

**Comment by nth10sd** [comment]
Thanks for sharing your plans for removing `--statistics` and `--count`, I'll remove them from my configs then.
