### ISSUE TITLE
yesqa broken by flake8 update.

### ISSUE THREAD

**Issue by jschwartzentruber** [asottile/yesqa#150]
yesqa seems to need an update since flake8 6.0 was released. It's stripping `noqa` flags out, which causes flake8 to fail later in the pre-commit run. I haven't investigated further yet.

```
Strip unnecessary `# noqa`s..............................................Failed
- hook id: yesqa
- exit code: 1
- files were modified by this hook
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/__main__.py", line 7, in <module>
    raise SystemExit(main())
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
Rewriting grizzly/reduce/core.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/__main__.py", line 7, in <module>
    raise SystemExit(main())
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
  File "/home/worker/.cache/pre-commit/repor01pxoqb/py_env-python3/lib/python3.8/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
Rewriting grizzly/common/fuzzmanager.py
```

This is happening in CI for https://github.com/MozillaSecurity/grizzly/commit/1bcd05622ca261ed154b2fb1fd10915ed837fba2 ([CI log](https://community-tc.services.mozilla.com/tasks/WMs3XUjRQIChfzgPRltcFA/runs/1/logs/public/logs/live.log))

**Comment by asottile** [comment]
yep -- these inline comments [are incorrect](https://flake8.pycqa.org/en/latest/user/configuration.html) (search around for the warning): https://github.com/MozillaSecurity/grizzly/blob/1bcd05622ca261ed154b2fb1fd10915ed837fba2/tox.ini#L59-L60
